repos:
-   repo: https://github.com/ambv/black
    rev: 23.10.0
    hooks:
    - id: black
      language_version: python3.11

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-ast

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the latest available version
    hooks:
    -   id: isort
        args: ["--profile", "black"]
